// <auto-generated />
namespace DataAcceessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_add_tblMessagess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_add_tblMessagess));
        
        string IMigrationMetadata.Id
        {
            get { return "202208171920384_mig_add_tblMessagess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
